import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";
import CartIcon from "@/components/CartIcon";
import Navigation from "@/components/Navigation";

const bebasNeue = Bebas_Neue({
  variable: "--font-urban-heading",
  weight: "400",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-urban-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${montserrat.variable} antialiased bg-[#020202] text-[#FAFFFD]`}
      >
        <AuthProvider>
          <CartProvider>
            {children}
            <CartIcon />
            <Navigation />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
