import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";
import CartIcon from "@/components/CartIcon";
import Navigation from "@/components/Navigation";

const bebasNeue = Bebas_Neue({
  variable: "--font-urban-heading",
  weight: "400",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-urban-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${montserrat.variable} antialiased text-[#FAFFFD] relative min-h-screen`}
      >
        {/* Background Video */}
        <div className="fixed inset-0 -z-10 bg-[#020202]">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="w-full h-full object-cover opacity-40 grayscale-[20%]"
          >
            <source src="/assets/pizza-bg.mp4" type="video/mp4" />
          </video>
          {/* Overlay to ensure legibility */}
          <div className="absolute inset-0 bg-[#020202]/30" />
        </div>

        <AuthProvider>
          <CartProvider>
            {children}
            <CartIcon />
            <Navigation />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
